### ISSUE TITLE
The notification count stays out of date

### ISSUE THREAD

**Issue by jaydlawrence** [searleb/quickhub#1]
**Describe the bug**
After I clear the notifications on GitHub, the extension still shows the old count.
I can't figure out a way to refresh it.

**To Reproduce**
1. If you have notifications unread on github
2. Go to github and mark them done or read so that on github the count is 0
3. The extension still shows the previous number

**Expected behavior**
After clearing the count, it should update the count number.

**Screenshots**
![Screen Shot 2020-11-16 at 6 25 35 PM](https://user-images.githubusercontent.com/1242060/99315513-2392c400-2839-11eb-887c-71b38b62588b.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Browser: Chrome
 - Version: 86

**Comment by searleb** [comment]
@searleb test

**Comment by searleb** [comment]
@jaydlawrence this is a weird one, it seems the github api takes an age to update. The app fetches the notifications each time you open it and should poll for them every 15 mins (although I think this process stops when the background.js goes to sleep so I might just take it out)

**Comment by searleb** [comment]
I think this has been fixed by setting the background.js to persistent in the manifest.json
